# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "fgraph"
  s.version = "0.6.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Herryanto Siatono"]
  s.date = "2011-11-19"
  s.description = "Ruby Facebook Graph API"
  s.email = "herryanto@gmail.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "History",
    "License",
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "examples/get_access_token.rb",
    "examples/publish_feed.rb",
    "lib/fgraph.rb",
    "lib/fgraph/client.rb",
    "lib/fgraph/rails/fgraph_helper.rb",
    "lib/fgraph/rails/fgraph_tag_helper.rb",
    "lib/tasks/fgraph.rake",
    "lib/tasks/fgraph.rb",
    "rails/init.rb",
    "templates/fgraph.yml",
    "test/fgraph/client_test.rb",
    "test/fgraph_test.rb",
    "test/fixtures/access_token.txt",
    "test/fixtures/object_cocacola.json",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/jugend/fgraph"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Ruby Facebook Graph API"
  s.test_files = [
    "examples/get_access_token.rb",
    "examples/publish_feed.rb",
    "test/fgraph/client_test.rb",
    "test/fgraph_test.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0.5.0"])
      s.add_development_dependency(%q<shoulda>, ["~> 2.10.0"])
      s.add_development_dependency(%q<mocha>, ["~> 0.9.0"])
      s.add_development_dependency(%q<fakeweb>, ["~> 1.2.0"])
    else
      s.add_dependency(%q<httparty>, [">= 0.5.0"])
      s.add_dependency(%q<shoulda>, ["~> 2.10.0"])
      s.add_dependency(%q<mocha>, ["~> 0.9.0"])
      s.add_dependency(%q<fakeweb>, ["~> 1.2.0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0.5.0"])
    s.add_dependency(%q<shoulda>, ["~> 2.10.0"])
    s.add_dependency(%q<mocha>, ["~> 0.9.0"])
    s.add_dependency(%q<fakeweb>, ["~> 1.2.0"])
  end
end

